### ISSUE TITLE
Formalize Problem Statement & Goals Document

### ISSUE THREAD

**Issue by tsaruggan** [tsaruggan/capstone#16]
Complete the following sections of the Problem Statement deliverable:

1. Problem Statement
1.1. Problem - Abstractly state the problem to be solved. State why the problem is important and give context. 
1.2. Inputs & Outputs - Characterize the problem in terms of inputs and the outputs.
1.3. Stakeholders
1.4. Environment (for the software/hardware)
2. Goals - ~5 measurable goals for minimum viable product
3. Stretch Goals - Ambitious goals

Refer to lecture 2 for more examples and detail

**Comment by aniketkabra** [comment]
Initial problem statement draft: https://github.com/tsaruggan/capstone/pull/21

**Comment by tsaruggan** [comment]
According to the Food Waste Statistics in Canada 2023, over 50 million tonnes of food are wasted every year while 1 in 8 Canadian families are dealing with food insecurity. This issue proves not be a resource or financial issue but rather a logistical one. 



This problem makes it necessary to rescue food and feed the families in need. Currently, there exists an intricate network of non-profit food rescue organizations and charities which mainly deal in bulk food rescue. 

Through this project, we aim to build a mobile application that will help connect drivers directly to individuals facing hunger. These volunteer drivers will pick up the food from the food banks, and perform micro-deliveries to individuals in need. This is a multi-tiered solution, as it solves the problem of food waste, while also fixing the growing food insecurity crisis.

**Comment by tsaruggan** [comment]
**Stakeholders**:

Project Advisors: Dr. Elkafi Hassini, Ahana Malhotra, and Sujana Saha are clients for the project and are responsible for the high-level vision and overseeing the execution of the product.

**Comment by aniketkabra** [comment]
**Adding Goals**:

- Live order tracking:
The system should be able to track the driver and show their location to the recipient in real time. This will allow the recipient to know the estimated time of delivery and the whereabouts of their driver.

- Notify recipients with order status:
The system should be able to send notifications to the drivers about the status of their pick-up order. Furthermore 

- Provide drivers with step-by-step directions:
